name = "CorrelationTrackers"
uuid = "2aaf3720-2af0-4ca4-b7d9-7d970023fcad"
authors = ["Vasily Postnicov <shamaz.mazum@gmail.com>"]
version = "0.6.8"

[deps]
AnnealingAPI = "ea73c536-af4e-4c29-9508-d79bc79c0161"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
CorrelationFunctions = "cd8c4018-4f35-43b7-8520-d042ebaeaa2d"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AnnealingAPI = "0.2"
CircularArrays = "1.2"
CorrelationFunctions = "0.8"
Interpolations = "0.13, 0.14"
Reexport = "1.1.0"
julia = "^1.0"

[extras]
XUnit = "3e3c03f2-1a94-11e9-2981-050a4ca824ab"

[targets]
test = ["XUnit"]
